# Generated by Django 5.2.5 on 2025-08-06 17:29

import DevOps.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=100)),
                ('github_username', models.CharField(help_text='GitHub username of the project owner', max_length=39, validators=[DevOps.models.validate_github_username])),
                ('database_name', models.CharField(help_text='Database name for the project', max_length=63, validators=[DevOps.models.validate_database_name])),
                ('domain_name', models.CharField(help_text='Domain name for the project deployment', max_length=253, validators=[DevOps.models.validate_domain_name])),
                ('project_github_link', models.URLField(help_text='GitHub repository URL for the project', max_length=500)),
                ('project_details', models.TextField(help_text='Detailed description of the project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployment_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('maintenance', 'Under Maintenance')], default='pending', help_text='Current deployment status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the project is active')),
                ('owner', models.ForeignKey(help_text='User who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'project_name')},
            },
        ),
    ]
