# Generated by Django 4.2.20 on 2026-07-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectinvitation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('invitee__isnull', False)), fields=('project', 'invitee'), name='unique_project_invitee'),
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('project', 'email'), name='unique_project_email'),
        ),
    ]
